#!/usr/bin/env python

import os
import sys

cwd = os.getcwd()
prunefile = None

while True:
  for ext in ['', '.py']:
    for pf in ['prunefile', 'Prunefile']:
      pf = os.path.join(os.path.abspath(cwd), pf + ext)
      if os.path.exists(pf): prunefile = pf

  if prunefile: break

  parent = os.path.dirname(cwd)
  if cwd == parent: break
  cwd = parent

if not prunefile:
  print('prunefile not found')
  sys.exit(1)

from importlib.util import spec_from_loader, module_from_spec
from importlib.machinery import SourceFileLoader

spec = spec_from_loader('prunefile', SourceFileLoader('prunefile', prunefile))
_prunefile = module_from_spec(spec)
spec.loader.exec_module(_prunefile)
